name: Build
on:
  push:
    branches-ignore:
      - data
      - gh-pages
    tags:
      - '**'
  pull_request:
    branches-ignore:
      - data
      - gh-pages

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          architecture: x64

      - name: Create virtual environment
        run: python -m venv venv

      - name: Set up environment variables
        run: |
          echo "VIRTUAL_ENV=$(pwd)/venv" >> $GITHUB_ENV
          echo "$(pwd)/venv/bin" >> $GITHUB_PATH

      - name: Activate virtual environment and verify Python version
        run: |
          source venv/bin/activate
          python --version

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install buildozer pyjnius

      - name: Verify pyjnius version
        run: |
          source venv/bin/activate
          python -c "import jnius; print(jnius.__version__)"

      - name: Build with Buildozer
        run: |
          source venv/bin/activate
          cd master
          buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: master/bin/*.apk

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: data
          ref: data # Branch name

      #- name: Push binary to data branch
      #  if: github.event_name == 'push'
      #  run: python master/.ci/move_binary.py "${{ steps.buildozer.outputs.filename }}" master data bin
