name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        echo "source venv/bin/activate" >> $GITHUB_ENV
        echo "VIRTUAL_ENV=venv" >> $GITHUB_ENV
        echo "PATH=venv/bin:$PATH" >> $GITHUB_ENV

    - name: Verify Python version
      run: |
        source venv/bin/activate
        python --version
